repos:
    - repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
        - id: black
          language_version: python3
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
        - id: trailing-whitespace
        - id: flake8
        - id: detect-private-key
        - id: debug-statements
        - id: check-yaml
        - id: end-of-file-fixer
        - id: check-ast
        - id: check-json
        - id: check-docstring-first
        - id: check-added-large-files
        - id: check-merge-conflict
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: 'master'
      hooks:
        - id: isort
